---
driver:
  name: docker
platforms:
  - name: ssh-key-rotation-rollback-ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: /usr/sbin/init
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
    groups:
      - rotate
  - name: ssh-key-rotation-rollback-rockylinux9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    command: /usr/sbin/init
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
    groups:
      - rotate
  - name: ssh-key-rotation-rollback-rockylinux10
    image: geerlingguy/docker-rockylinux10-ansible:latest
    command: /usr/sbin/init
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
    groups:
      - rotate
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../roles"
  inventory:
    group_vars:
      rotate:
        ansible_remote_tmp: /root/.ansible/tmp
scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: ansible
